# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


# API DEPARTMENT MANAGEMENT

GET {{host-url}}/departments

###

POST {{host-url}}/departments
Content-Type: application/json

{
  "name":"Ministry of Education",
  "description":"The Ministry of Education is the ministry responsible for secondary, vocational and tertiary education in Bangladesh. Primary education and mass literacy is the responsibility of the Ministry of Primary and Mass Education"
}

###

PATCH {{host-url}}/departments/1
Content-Type: application/json

{
  "name":"Ministry of Education update patch"
}

###

PUT {{host-url}}/departments/1
Content-Type: application/json

{
  "name":"Ministry of Education update put",
  "description":"The Ministry of Educations is the ministry responsible for secondary, vocational and tertiary education in Bangladesh. Primary education and mass literacy is the responsibility of the Ministry of Primary and Mass Education"
}

###

##



# API DESIGNATION MANAGEMENT
GET {{host-url}}/designations

###

POST {{host-url}}/designations
Content-Type: application/json

{
  "name":"Upazila Livestock Officer"
}

###

PATCH {{host-url}}/designations/1
Content-Type: application/json

{
  "name":"Software engineer patch update"
}

###

PUT {{host-url}}/designations/1
Content-Type: application/json

{
  "name":"Software engineer put update"
}

###

##





